name: favorite_places
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_riverpod: ^3.0.0
  google_fonts: ^6.3.1
  image_picker: ^1.2.0
  location: ^8.0.1
  uuid: ^4.5.1
  url_launcher: ^6.2.5
  mapbox_maps_flutter: ^2.11.0
  flutter_dotenv: ^6.0.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/image/
